### ISSUE TITLE
Measure `getHandle()` performance

### ISSUE THREAD

**Issue by linas** [opencog/benchmark#16]
One key activity is getting Nodes by name, and Links by outgoing set.  This is not measured currently, it should be.

**Comment by linas** [comment]
closing. WTF. github has gone insane.  Duplicate of #15

**Comment by linas** [comment]
clsoing. Again why won't this stay closed?  Duplicate of #15

**Comment by linas** [comment]
Closing. Try number 3 -- github is broken today!?

**Comment by ngeiswei** [comment]
I'm having that sort of problems too but I suspect it comes from the latest versions of Firefox (if you use that) that attempt to keep a cache (including of your own edits) and such...

**Comment by linas** [comment]
Yeah, this was with firefox; but not the latest version. Hmm OK, thanks. never saw this before.

**Comment by AmeBel** [comment]
https://status.github.com/messages github was having issues during that time
