### ISSUE TITLE
Move make_benchmark_graphs.py scripts from atomspace to benchmark repo

### ISSUE THREAD

**Issue by vsbogd** [opencog/benchmark#7]
File [make_benchmark_graphs.py](https://github.com/opencog/atomspace/blob/master/scripts/make_benchmark_graphs.py) is part of opencog/benchmark/atomspace/atomspace benchmarkin.
Todo:
- move make_benchmark_graphs.py into benchmark repo
- fix atomspace/atomspace/README.md using new file location

**Comment by linas** [comment]
Yeah, move the contents of `https://github.com/opencog/atomspace/blob/master/scripts/query` as well. Honestly, I didn't even know that these scripts existed, until just now.  The vast, incredible power of cruft-accumulation.

**Comment by vsbogd** [comment]
Only two of them are related to benchmarking:
- atomspace/scripts/query/benchmark_query.sh
- atomspace/scripts/benchmark_utests.sh
Both scripts run unit tests in a loop and show timings. I would replace them by benchmarks. @ngeiswei, it seems you are an author, what do you think?

**Comment by ngeiswei** [comment]
I see two problems with moving them to the benchmark repo

1. it's harder to find the build directory of the atomspace repo from the benchmark repo,
2. unit tests performances are not intended to reflect real world performances.

So if they are being moved, to minimize these problems I suppose one could
1. assume by default that atomspace repo folder is beside the benchmark repo folder, that will probably work for most people,
2. printing a big warning of its shortcomings in the corresponding `README.md` and/or as a message at script launch.

If that is respected I think it would be acceptable to move them to the benchmark repo.

**Comment by vsbogd** [comment]
@ngeiswei, I didn't mean these scripts should be literally "moved". I think more proper way is adding new benchmarks (for instance under https://github.com/opencog/benchmark/issues/8) and removing these shell scripts.

**Comment by linas** [comment]
this has been done, so this bug can be closed, right?

**Comment by vsbogd** [comment]
Yes, closing it, new tests to be added under https://github.com/opencog/benchmark/issues/8
